{"name": "查询题目及做题记录", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <case.6noble_ApiTest.Test_ApiCase object at 0x0000020A28790070>\nApi_Token = (<KeyWords.Api_Keys.api_keys object at 0x0000020A28790A60>, 'eaaf917e9c654797b0f2aacaf17259d5', <Logger logger (DEBUG)>)\n\n    @allure.story(\"04.查询题目以及答案和已答题记录\")\n    @allure.severity('normal')\n    def test_04(self, Api_Token):\n        ak,token,log = Api_Token\n        allure.dynamic.title('查询题目及做题记录')\n        with allure.step(\"接口返回正确的返回值\"):\n            url = URL + ReadIni('../conf/config.ini','ANSWER_PATH','path')\n            userdata = {\n                'formId': Test_ApiCase.formId,\n                'token': token,\n                'publicKey': publicKey,\n                'scaleId':Test_ApiCase.scaleId\n            }\n            res = ak.post(url=url, data=userdata)\n        with allure.step('获取题目及答案'):\n            questionIds=[]\n            questionId=jsonpath.jsonpath(res.json(),'$.data..getEvluationQuestionAndAndwerVo[*].evaluationAnwsers[0].questionId')\n            answerIds=[]\n            answerId=jsonpath.jsonpath(res.json(),'$.data.result..getEvluationQuestionAndAndwerVo[*].evaluationAnwsers[*].anweserId')\n            questionIds.append(questionId)\n            answerIds.append(answerId)\n>           print(answerIds[1],questionIds[1])\nE           IndexError: list index out of range\n\n6noble_ApiTest.py:102: IndexError"}, "steps": [{"name": "接口返回正确的返回值", "status": "passed", "steps": [{"name": "发送post请求", "status": "passed", "parameters": [{"name": "url", "value": "'https://hapi.6noblexc.com/api/6nobleapi/qnr/evaluationQuestion/getEvaluationQuestionsRequestVo'"}, {"name": "data", "value": "{'formId': 'e0cd9ef7f15411eca26700161398', 'token': 'eaaf917e9c654797b0f2aacaf17259d5', 'publicKey': 'pvj9bTwwaY4YdPiwRBH5RE25o9ZM8BHG', 'scaleId': 'SCALE110550138870982656066376'}"}], "start": 1656494223406, "stop": 1656494223605}], "start": 1656494223405, "stop": 1656494223605}, {"name": "获取题目及答案", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"D:\\work\\pythonProject(1)(1)\\pythonProject\\case\\6noble_ApiTest.py\", line 102, in test_04\n    print(answerIds[1],questionIds[1])\n"}, "start": 1656494223605, "stop": 1656494223658}], "start": 1656494223405, "stop": 1656494223658, "uuid": "aa70c94a-9e8a-4642-9c85-be65b0de1970", "historyId": "6bb2db8f1a1edb4a88c5b6a120882eee", "testCaseId": "7a81eb0acf47483136f9e040538a96bc", "fullName": "6noble_ApiTest.Test_ApiCase#test_04", "labels": [{"name": "severity", "value": "normal"}, {"name": "story", "value": "04.查询题目以及答案和已答题记录"}, {"name": "epic", "value": "智慧云3.0新平台"}, {"name": "suite", "value": "6noble_ApiTest"}, {"name": "subSuite", "value": "Test_ApiCase"}, {"name": "host", "value": "DESKTOP-FA1JTDA"}, {"name": "thread", "value": "24460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "6noble_ApiTest"}]}